# Generated by Django 4.2.13 on 2024-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_headerimage_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='introduction/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='HeaderImage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
